version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    deploy:
      replicas: 3
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  redis:
    image: redis:latest
    deploy:
      replicas: 3
    restart: always
    networks:
      - redis-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  mongo-network:
    external: true
  redis-network:
    external: true

volumes:
  mongo_data:
  redis_data:
